### ISSUE TITLE
Handle multiple inputs with the same label

### ISSUE THREAD

**Issue by jscn** [aloetesting/aloe_webdriver#11]
When I upgraded from lettuce-webdriver to aloe-webdriver, some of my tests which use the Django admin started failing because there were multiple fields with the same label. Normally that would be fine, but it was a little hard to debug because the offending extra form is not visible.

It just so happened that I only hit the error on pages with inline forms where more than one related model could be created. In this case, Django hides an extra form in the page HTML so that it can create new forms on the fly for adding extra related models. These (hidden) forms have fields with the same label as the (only) visible form, and so the tests started failing because `aloe-webdriver` was finding multiple fields with the same label.

I'm not sure this is exactly a bug, but maybe `aloe-webdriver` could emulate `lettuce-webdriver` here and pick the first matching item (I'm assuming that's the `lettuce-webdriver` behaviour), or maybe `find_field` could ignore non-visible elements by default.

**Comment by koterpillar** [comment]
Does #12 solve your problem?

**Comment by koterpillar** [comment]
Fixed in #12, please comment if this is still an issue.
