### ISSUE TITLE
PhantomJS Performance

### ISSUE THREAD

**Issue by gdiscry** [aloetesting/aloe_webdriver#15]
I am currently evaluating Aloe to replace a frozen and customized version of Lettuce in our projects (because upgrading Lettuce brings even more pain).

So far, the migration path is encouraging and I managed to convert a small project from Lettuce WebDriver to Aloe WebDriver. However, I noticed a big drop in performance when the PhantomJS webdriver is used.

I've set up a small example at https://github.com/gdiscry/aloe-webdriver-benchmark (Python 2.7) to profile the execution of the tests under both frameworks. You can see the difference by running the following commands:

``` sh
# Create virtualenv
pip install -r requirements.txt
time python profile.py
time LETTUCE=1 python profile.py
```

On my machine, Lettuce runs the tests in **2s** and Aloe in **14s**. After profiling the execution, the performance hit seems to come from the number of XPath commands executed by Selenium in PhantomJS. For both Lettuce WebDriver and Aloe WebDriver, some XPath commands sent to PhantomJS take **~200ms** to complete.

With the example I made, Lettuce WebDriver executes **2** such commands while there are **58** for Aloe WebDriver.

I think they are linked to the `aloe_webdriver.fill_in_textfield` step. Maybe the XPath requests should be merged together so that there is only one for that step.

I tested the example with Aloe 0.0.35, Aloe WebDriver 0.4.2 , Lettuce 0.2.21, Lettuce-WebDriver 0.3.5, Selenium 2.48.0 and 2.33.0 and finally PhantomJS 2.0.0 and 1.9.8.

**Comment by koterpillar** [comment]
I tracked this down to Aloe calling `is_displayed` (and `is_enabled`) on the elements, and not merging the XPath queries properly; watch https://github.com/koterpillar/aloe_webdriver/pull/16 for progress (and please try that branch to see if it speed things up).

**Comment by koterpillar** [comment]
Can you please test the new version (0.4.4) and see if it makes things better?

**Comment by gdiscry** [comment]
The performance of the new version is really better now and on par with Lettuce. I'll start porting a bigger project soon.

Thanks for the fix and the responsiveness !
